### ISSUE TITLE
Overlapped I/O operation is in progress.

### ISSUE THREAD

**Issue by bruhov** [ufrisk/MemProcFS#104]
Hi,
thank you for your great project, I've been using it for almost two years.

I use ScreamerM2 R03.
I have a tool that actively reads and writes to a process's memory in real time.
Recently I updated it and PCILeech components:
**PCILeech-FPGA**: 4.6 => 4.9
**MemProcFS**:  3.2 => 4.9.2

There was a problem after the update. If I call VMMDLL_Initialize with the default algorithm, then VMMDLL_MemReadScatter throws the error "Overlapped I/O operation is in progress.". However, if I specify `algo=1` or `algo=2` everything works fine.

Here is my VMMDLL_* calls log:
```
01:25:41.480 - VMMDLL_Initialize
01:25:44.057 - VMMDLL_PidGetFromName
01:25:44.057 - VMMDLL_Map_GetModuleFromName
01:25:44.199 - VMMDLL_MemReadScatter
01:25:44.199 - VMMDLL_MemReadScatter
01:25:44.199 - VMMDLL_MemReadScatter
01:25:44.199 - VMMDLL_MemReadScatter
01:25:44.200 - VMMDLL_MemReadScatter
01:25:44.200 - VMMDLL_MemReadScatter
01:25:44.201 - VMMDLL_MemReadScatter
panic: VMMDLL_MemReadScatter: Overlapped I/O operation is in progress.
```

**Comment by ufrisk** [comment]
Thanks for reporting this :)

I changed the default read algorithm to use some overlapped IO about two years ago to speed things up a tiny bit. It's the first time I've seen some issues around this. But it's good to see the other algorithms seem to be working. But still it shouldn't cause errors and I'm guessing the small performance increase would be nice.

I'm guessing you're running on Windows? With the most recent `FTD3XX.dll`? Are you consuming the C library from C++?

Since I haven't seen this behavior before would you be able to replicate this issue consistently with a small test program?

**Comment by ufrisk** [comment]
Huge thanks for the demo project :) I'm currently away from home (no access to hardware) so it may take a little while before I'm able to look into this.

**Comment by ufrisk** [comment]
Thanks. I have located the issue and will be fixing it in the next version. Unfortunately that may be some time away since I'm in the middle of a rewrite of that code (for some additional performance).

If the issue is causing you pain until then you may start with the parameter -device fpga://algo=2  (which won't use the overlapped reading).

**Comment by ufrisk** [comment]
Apologies for the long wait on this issue. I never though it to be very important, but with fixes (and performance boost) I released today it should now be fixed.

Please let me know if you should still be experiencing this issue (and in that case also please reopen the issue). I really hope it should be resolved now though.
