### ISSUE TITLE
VMMDLL_Map_GetEATU sometimes failing.

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#107]
to get VMMDLL_Map_GetEATU working, sometimes needs a lot of system restart until its working. I did the same as example written. Thank you so much!.

**Comment by ufrisk** [comment]
Most likely reason for this is that Windows after a while pages out necessary data structures to the page file. This makes MemProcFS unable to read exports.

The issue should go away for a short while after a single system reboot though. That you require multiple reboots (if accessing the VMMDLL_Map_GetEATU shortly after startup is strange, can you please confirm this is not the issue).

If your issue is paging there is unfortunately not anything I'm able to do about this. As a workaround you could read the addresses when it's working. The offsets relative to the module base should stay the same for most symbols unless there is a new version of the specific module.

Can you please confirm is starts working after a reboot of the target system if you access it kinda quickly afterwards? If so it's 100% a paging issue and you may close this issue.

**Comment by 0xGabriella** [comment]
ah okay ulf, thank you so much for your reply. Seems like the issue cant be resolved, but i can try manual walk the exports using memory read only.  Anyway great project!.
