### ISSUE TITLE
Not really an issue with timeline_all

### ISSUE THREAD

**Issue by antmar904** [ufrisk/MemProcFS#109]
Hi.

Great tool and thank you for your work.  Is there an easier way to view/read timeline_all file as it contains a lot of data?

**Comment by ufrisk** [comment]
No worries, and I'm glad to see you like the tool. Thanks :heart:

You should be able to import it in Elasticsearch or Excel if you look at the json version of it in the json directory.

Also it's great to do some simple grep on it if you mount the MemProcFS drive in WSL `mount -t drvfs M: /mnt/m`

I'm working on a CSV version of it as well in the next release which would allow you to use Zimmerman's timeline explorer as well.

**Comment by antmar904** [comment]
Got it thank you. I love Zimmerman tools!

**Comment by ufrisk** [comment]
Awesome! The release is due in a few weeks / a month or so, so there will be a short wait. It will be a major one with lots of small improvements, mainly csv file generations. Keep an eye open for it and please let me know if you'd feel anything else is missing in MemProcFS and I'll try to do my best to add it.

I'm closing this issue since I feel you got a nice answer.
