### ISSUE TITLE
Unable to mount in Ubuntu on WSL

### ISSUE THREAD

**Issue by antmar904** [ufrisk/MemProcFS#111]
Hi.

I dl the git package and now I'm having issues mounting a .raw file in my Ubunut WSL.  Can you please explain how I can dl and install MemProcFS on Ubuntu WSL, install it and mount an image?  Thank you!

**Comment by ufrisk** [comment]
On Linux you'd need to do:

You'd need to install dependencies: `sudo apt-get install libusb-1.0 fuse openssl lz4` as per https://github.com/ufrisk/MemProcFS/wiki/_Linux

then do ./memprocfs -device /path/to/memory/image -mount /full/absolute/path/to/mount/point

---

If you mean using WSL to access the drive you mounted with MemProcFS Windows you'd need to first mount it on Windows then in WSL do `mount -t drvfs M: /mnt/m`

**Comment by ufrisk** [comment]
hm, it's working for me on Ubuntu 18.04/20.04/22.04.

also you'd need to be running WSL2 to be able to do the FUSE mount.

But why run it like this? It should work, but please know the Linux version is slightly less good. It currently does not support the compressed memory and online debug symbols since the functionality I use rely to some degree on the windows api. A better alternative would be the mount it in Windows and then mount in WSL using drvfs - as root: `mount -t drvfs M: /mnt/m`

**Comment by ufrisk** [comment]
I'm assuming you got this to work. I'm closing the issue, but if you should still have any issues please let me know in this issue.
