### ISSUE TITLE
Why is the acquisition sometimes delayed for a long time? What should I do best?

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#129]
Why is the acquisition sometimes delayed for a long time? What should I do best?
Is that so? I add try to the loop. It seems that it will get stuck after running for a period of time. I don't understand why.

```
while(true){
 VmmScatter scatter = vmm.Scatter_Initialize(pid, Vmm.FLAG_NOCACHE);
                            scatter.Prepare(GameState + Offset_LerpSafetyZoneRadius, 4);
scatter.Execute();
scatter.Execute();
      var lerpSafetyGasRadius = scatter.Read(GameState + Offset_LerpSafetyZoneRadius,4);
scatter.Clear(pid, Vmm.FLAG_NOCACHE);
}
```

**Comment by ufrisk** [comment]
The PCILeech and MemProcFS projects were created for DMA attacks and security research. I know it's in use for game cheats as well. It was not a use case I anticipated and I don't really mind. But I wish to stay away from it myself. Please keep questions about how to hack games, games offsets and such on other forums more suitable for the subject rather than on my github.

I'll do my best to answer general questions, but I'm not actively going to help you cheat.

Thanks for understanding.

**Comment by bbhxwl** [comment]
> The PCILeech and MemProcFS projects were created for DMA attacks and security research. I know it's in use for game cheats as well. It was not a use case I anticipated and I don't really mind. But I wish to stay away from it myself. Please keep questions about how to hack games, games offsets and such on other forums more suitable for the subject rather than on my github.
> 
> I'll do my best to answer general questions, but I'm not actively going to help you cheat.
> 
> Thanks for understanding.

I didn't say the problem of cracking the game. I just asked the best method of cyclic reading. What is the most efficient?

**Comment by ufrisk** [comment]
Yes, but in your example you have things like GameState and such. It's pretty clear what you wish to do here. And I don't wish to get involved in cheats.
