### ISSUE TITLE
Variance in ellapsed time multiple successive mem reads

### ISSUE THREAD

**Issue by leolongvu** [ufrisk/MemProcFS#13]
Hi Ufrisk

While testing for the performance of the interop C# I noticed something strange. I have a loop which calls VMM_MemReadEx with VMMDLL_FLAG_NOCACHE about 200 times. I cannot read all of them in one go because there are some addresses which provide pointers to other addresses and even with some sort of encryption. The average total ellapsed time is about 40ms but I saw some bumps at 300ms-400ms in between. 

So I thought I would test them again with the original C lib, I just grab the PID of notepad and read at base address 500 times. Result is in the pic below:

![image](https://user-images.githubusercontent.com/23338990/67638591-20e7c880-f8de-11e9-9bc5-f14a06069f94.png)

As you can see there are two bumps after about 30 reads, sometimes more sometimes less. I wonder what might have caused this and is there a way to mitigate.

Leo

**Comment by ufrisk** [comment]
I'll assume you use the PCIeScreamer and that you're reading the same addresses in the loop.

vmm.dll have a built-in refresh of the process list and the page table caches every now and then, default is every 5s - this may be your issue since the time period somewhat indicates this. You can try to disable with: `VMMDLL_ConfigSet(VMMDLL_OPT_CONFIG_TICK_PERIOD, 0xFFFFFFFF);` or something like that. There are also other related options to this.

The PCIeScreamer is also somewhat unstable and if an instability is detected the underlying LeechCore library will attempt to recover. This will take some time as well. I don't think this is your issue since it's quite random when it happens - but for this I have no solution.

Also, some reads may be slower if you read "paged out" memory which may result in many physical reads. If you are reading the same addresses in a loop this is not your issue. I'm currently rewriting the virtual memory sub-system so I expect this to be a lot more common in next release, but I'll have flags to mitigate.

**Comment by leolongvu** [comment]
The refreshing is indeed the the underlying problem. I am surprise that I did not find out about this as I have already play with the read delay. Many thanks for the solution.

**Comment by QuiNz0r** [comment]
@leolongvu did you have any success with your C# implementation? I wrote my own library in C# with interop but I'm having a big headache on translating the passed variable types since I'm a C beginner. Did you come up with anything usable?
