### ISSUE TITLE
Some allocated pools not listed in memprocfs

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#131]
Hello Ulf, wishing you good luck as always.

https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/updating-deprecated-exallocatepool-calls

Based on this, 2004 and later windows versions already have new implementation on how to allocate kernel memory. Does this update affects current function on memprocfs that dumps pools (VMMDLL_Map_GetPool) ? Because some pools i found on windows are not listed in the returned data by the function even by providing VMMDLL_POOLMAP_FLAG_ALL flag. Thank you!.

**Comment by ufrisk** [comment]
Hi, and many thanks :)

I don't think the new API should change the pool parsing as-per-say.

But there may be fairly recent changes that makes some allocations go missing. To investigate this I would really need an example of a missing memory allocation that should be there and info about it, pretty much a paused VM or a memory dump. Or a known way to generate pool allocated memory not visible in MemProcFS. A test driver or similar.

Are you experiencing memory allocated with the pool api that is missing from MemProcFS if a new memory dump or a new connection is made? Also this may happen due to caching so checking if anything is missing on a new MemProcFS instance would be important.

**Comment by 0xGabriella** [comment]
sorry for late reply Ulf, i was on business trip in Japan. Btw the issue was indeed correct as you said, the caching was the problem. After pc restarted all back to normal!. Thank you.

**Comment by ufrisk** [comment]
Huge thanks for letting me know, and good luck with everything :)
