### ISSUE TITLE
read content of kernel pools

### ISSUE THREAD

**Issue by haode333** [ufrisk/MemProcFS#136]
Hi ufrisk,

I find that MemProcFS is able to generate content of kernel allocated pools ([here](https://github.com/ufrisk/MemProcFS/wiki/FS_SysInfo_Pool)).
I followed the example in vmm_examples to get pools but couldn't read any of the va returned.
I'm reading like ```VMMDLL_MemRead(hVMM, -1, ffffd582c5d02000, pbPage1, 0x1000);```
Am I doing it wrong?

**Comment by ufrisk** [comment]
you'd need to read from the kernel memory - i.e. PID 4 (not PID -1 as in your example).

Also the address need to be 0xffffd582c5d02000.

**Comment by haode333** [comment]
Hi ufrisk,

Thank you for the reply!
I tried PID = 4 but still no luck.
I'm now reading like ```auto status = VMMDLL_MemRead(hVMM, 4, pPoolMapEntry->va, pbPage1, 0x1000);``` and status is always 0.
I also tried ```VMM_Virt2Phys``` with PID = 4 and it returns FALSE as well.

Is there anything else I can try and maybe provide you with more information?

Thanks in advance!

**Comment by haode333** [comment]
Too add more information,

I tried to use ```va = VMMDLL_ProcessGetModuleBaseU(hVMM, 4, "ntoskrnl.exe");``` and it works fine.
reading memory from above va works fine too.

Only reading the pool doesn't work.

**Comment by ufrisk** [comment]
I don't see anything wrong with your memory read. The read size should be the size of the pool entry, but that will only fail in very rare circumstances with a bit too large read so I don't think that's the issue.

Is there a pool entry at the address? I guess so since you're retrieving the virtual address from a pool map entry, which I assume you got from `VMMDLL_Map_GetPool()`.

If you look at the specific entry, does it say to which kind of pool it belongs to? if pPoolMapEntry->tpPool is 3 then it's PagedPool and the entry may be paged out to disk - in which case it won't be able to read.

Also the PoolMap is really slow to generate so cache it for a long time. The entry may have been free'd in-between pool map generation and your read. You may force generate a new one by first calling `VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_SLOW, 1);` before calling `VMMDLL_Map_GetPool()` again.

**Comment by haode333** [comment]
> The read size should be the size of the pool entry

can you please elaborate on this? Do you mean there's a pool entry structure at the start of the pool (pPoolEntry->va)?

for type it's 2 (NonePagedPoolNx). However I don't find this information online. All I can find is that a pool can be either Paged or NonePaged, not sure about the 'Nx'.

Also thanks for the tip! It's indeed very slow XD I'll make sure to cache them if I can get this reading issue resolved.

**Comment by ufrisk** [comment]
No, there is no pool structure at the start of the virtual address in pPoolEntry->va, it should be before that.

About the caching, I didn't mean you should cache it. MemProcFS caches it automatically, but sometimes you may be looking at an old cached copy and may wish to clear it (and fetch pool data anew) with the function call I showed earlier on.

I really have no idea why it's failing for you. It seem to be pretty strange if it's in the NonPagedPool. Does it work if you try to read a smaller size, like size=0x10?

**Comment by haode333** [comment]
I tried setting ```VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_SLOW, 1);``` before get pool with no luck.

I also tried reading small sizes (0x4, 0x8, 0x10) without luck.

I also tried reading other pools (VS and BIG) without problem. seems only the specific pool I want to read is not working.

At this point I guess I'll have to compile memprocfs with symbols to see what's actually going on.

**Comment by haode333** [comment]
well it somehow magically works...
i'll see if it happen again.
Thanks for all the help Ufrisk!
