### ISSUE TITLE
MemProcFS + LiveCouldkd fails to connect to Hyper-v with dynamic RAM enabled

### ISSUE THREAD

**Issue by ullMarksin** [ufrisk/MemProcFS#145]
You have to uncheck dynamic memory on Hyper-v Manager, after that everything works fine. 

![screenshot](https://user-images.githubusercontent.com/39835173/201194301-8099b297-1a6d-4125-ab38-fa63dc8a9133.png)

**Comment by ullMarksin** [comment]
Maybe not issue, but should be mentioned in the documentation to uncheck dynamic memory 🤓

**Comment by ufrisk** [comment]
Many thanks for pointing this out. I've reflected it in the now updated documentation at: https://github.com/ufrisk/LeechCore/wiki/Device_LiveCloudKd

If you still believe it to be an error please raise the issue with the author gerhart01 at his https://github.com/gerhart01/LiveCloudKd

I hope this is now working better for you.

I'm closing this issue since I believe I've done what I can do about it.
