### ISSUE TITLE
vmm.PidList issue

### ISSUE THREAD

**Issue by sykoticnz** [ufrisk/MemProcFS#153]
I've got a problem that just cropped out and I can't figure it out - looking for help.

I'm using your MemProcFS C# API wrapper and suddenly the vmm.PidList() function is returning null. 

Specifically the 

`result = vmmi.VMMDLL_PidList(null, ref c);`

returns a false.

When I throw in a "-vv" to the initialize parameters I get the full process list being printed:

[PROCESS]  0014 (list) 0000716c 00055e8dc000 ffffc58f3bb57280 0055a32d3000 chrome.exe
[PROCESS]  0015 (exit) 00003198 0003a90b1000 ffffc58f43108080 00fd7c952000 notepad.exe
[PROCESS]  0016 (list) 00002190 0001992cd000 ffffc58f3aeed080 00c5210e6000 chrome.exe
[PROCESS]  0017 (list) 00004464 0004ba2a3000 ffffc58f3c9d5080 001d3397f000 rundll32.exe
[PROCESS]  0018 (list) 00003cd4 0002f2516000 ffffc58f4f1d50c0 000002e16000 CptHost.exe
[PROCESS]  0019 (list) 00006c84 000162d57000 ffffc58f429cc280 0070effda000 aomhost64.exe
[PROCESS]  0020 (list) 000032bc 0002a5304000 ffffc58f42846080 00000293b000 Zoom.exe

This proves that the memory reads are working. Just can't for the life of me figure out why the PidList() function is failing.

Any suggestions on what to check?

**Comment by sykoticnz** [comment]
I figured out the problem - it's not related to your code.

A particular anticheat program is messing with the PEB and/or DTB. This is making the PID's I'm looking for "invisible" to your "PIDGetFromName" function.

This happens on your current release of MemProcFS as well.

Interesting if Malware decides to mimic the same behavior to hide.

**Comment by ufrisk** [comment]
MemProcFS should be able to handle simple DKOM (like what is happening here) but it's not in this specific case.

It shouldn't be too hard to fix though, but I'm a bit hesitant since it have some performance implications in live memory mode. I would need to do this in the correct way. Also I'm a bit busy with other projects now, but it's on my todo list.

**Comment by sykoticnz** [comment]
Thanks @ufrisk .

I'm not quite following what they are doing - being it only occurs when when it's loaded it is making it tricky for me to debug it.

In lieu of you fixing it, could you put me in the rough direction of what is being messed with and then I can have a go at patching it myself.

Thanks.

**Comment by ufrisk** [comment]
Is the new version working better?

**Comment by sykoticnz** [comment]
Hi @ufrisk  - better, but still has issues.

The PidGetFromName function is returning the PID correctly now, however the ProcessGetModuleBase is failing to return any valid data.

**Comment by ufrisk** [comment]
It's because the DirectoryTableBase is broken/faked. You have to recover the correct one somehow and write it to the `dtb.txt` file in the process root folder to override the broken/faked one and things will start to work (if you write the correct one).

For hints you could check out the `M:\misc\procinfo\dtb.txt` for all the DirectoryTableBase addresses in the system. If you find one (or more) without a related process those are good candidates to try out. The file will take a short while to render.

Make sure you use the absolutely latest version since I made some updates recently.

Please let me know how it goes if you have any better success.

**Comment by sykoticnz** [comment]
Thanks @ufrisk  - can recover it manually and get access to the process using the info in your wiki.

Have you got any plans to implement this functionally (repointing the DTB) via your VMM APIs?

**Comment by ufrisk** [comment]
To set a custom DTB use:
```C
BOOL fResult = VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_PROCESS_DTB + dwPID, qwDTB);
```

To read a virtual file use:
```C
VMMDLL_InitializePlugins()   // only required once after startup

// do a read
BYTE pb[0x1000]
DWORD *pdbRead;
NTSTATUS nt = VMMDLL_VfsReadU(hVMM, "\\misc\\procinfo\\progress_percent.txt", pb, sizeof(pb), pcbRead, 0);
```

**Comment by sykoticnz** [comment]
Thanks @ufrisk - your help is greatly appreciated.

Still got a bit of work to do to get the file read working with in your C# API, but the VMMDLL_OPT_PROCESS_DTB option is working fine.

Fair to say you have fixed this "bug" I think.

**Comment by ufrisk** [comment]
I did a fairly nice performance upgrade recently as well so use the latest version.

Yes, the file system API isn't ideal in this case, but this is not core functionality so I can't go around adding separate API's for everything.

But good to see the issue is resolved. Best wishes in your projects and please let me know if you should run into something again.
