### ISSUE TITLE
set_config failing with the config ID OPT_REFRESH_FREQ_MEDIUM

### ISSUE THREAD

**Issue by yaellem** [ufrisk/MemProcFS#177]
Hello, 
First of all thank you a lot for your work it is awesome (especially the last released 5.5.0 which solves the problem of handle types and network connections with an fpga acquisition - screamer squirrel -)

I would like to talk about an issue I encountered while trying to set a config to the vmm using vmm.set_config() about the config ID OPT_REFRESH_FREQ_MEDIUM. I get a python error saying a constant used for a comparaison in the set_config() method is not defined, and when I set it manually with a random value the error disappear but it was just to try ^^
I put a screenshot to show the error : 

![error_set_config](https://user-images.githubusercontent.com/33577978/233361064-3de48248-0ba4-4f91-a5e5-0621c8982d6a.png)

And here are the lines in python :
![code_line_set_config_error](https://user-images.githubusercontent.com/33577978/233362895-3a51687e-b29f-4fa2-ba03-d2dc256b5925.PNG)

Also if you have more documentation about the refreshing settings I would be glad :) I would like to launch a refresing acquisition and check, like in the memprocfs + local software acquisition, for new processus on the targeted machine, instead of having to relaunch my python code by hand or by a script which is not fast and ugly ahah ^^
Thank you a lot in advance !
Have a great day !

**Comment by ufrisk** [comment]
Thanks for reporting. This should be fixed now, I messed up some constants.

Please let me know if it works for you once updating the pip package to 5.5.1

**Comment by yaellem** [comment]
I updated the package and it is working fine now, thank you :)  (I saw you removed some constant config options btw)

Would you have any advices in the use of the set_config method ? I try to refresh the acquisition as you do with the memProcFs command line tool (with a software acquisition directly on the target and with the fpga device acquisition too). 

From my python program I use an ugly while loop with : a Vmm['-device', 'fpga'] (.....) and a vmm.close() but I think there is a different way to do it using the REFRESH constants, the thing is I am not sure how to use it with set_config to achieve what I want.
In my POC I try to launch very fast processes to check if in the time of acquisition I can catch it (I report logs in a .txt file from my main loop then process_list loop).
Is there a correct way to use the set_config with appropriate constants ? I am sorry if it is not related to the error I reported, you do not have to loose time to explain me, but it would help me a lot to understand. 

Thank you very much in advance :)

Have a great day !

**Comment by ufrisk** [comment]
Awesome to see it's resolved. Thanks for the bug report 👍 

You could to a `set_config(memprocfs.OPT_REFRESH_ALL, 1)`

Alternatively only refresh the processes with `set_config(memprocfs.OPT_REFRESH_FREQ_MEDIUM, 1)` If you do this you may have to clear all cached memory as well with `OPT_REFRESH_FREQ_MEM` and `OPT_REFRESH_FREQ_TLB` prior to doing the `OPT_REFRESH_FREQ_MEDIUM` call.

I'm closing the issue since it seems to be resolved. Let me know if you should come across any other things not working.

**Comment by yaellem** [comment]
_**Network mapping refresh option:**_

Hello, 
I had a question and I was not sure if it was an issue in itself : 

Does the OPT_REFRESH_NET constant, defined in your C# code and displayed in the python wiki, is made to refresh the networking infos from the kernel memory ? 

Because for now the OPT_REFRESH_ALL is pretty slow (the same as closing and re-initializing the vmm object). I thought this constant was made for that but actually it is not defined in the memprocfs.py (which was not changed by the last version update actually), and neither it is in the vmmdll.h. 
I saw that constant was only defined in the C# code, do you think I can define it by myself locally ? (supposing it has the same value independantly of the language). Also some other constants are displayed in the wiki but not yet in the memprocfs.py 

**_Wiki :_** 
![image](https://user-images.githubusercontent.com/33577978/235863344-a506d645-3868-410b-a32b-95d881fb371e.png)
![github_constant_in_python_wiki](https://user-images.githubusercontent.com/33577978/235862759-f4c340ef-7d0e-49f0-a084-ca1b7e234662.png)

**_memprocfs.py:_** 
![image](https://user-images.githubusercontent.com/33577978/235863879-450471b4-a09f-4b0c-a7bc-4580d00f89e4.png)

**_C# sharp code by searching an occurence of the constant in the MemprocFs repository:_**
![github_constan_csharp](https://user-images.githubusercontent.com/33577978/235862770-e7fec2dc-b157-49e9-ae48-468101dc92d8.png)


Thank you a lot in advance and have a great day :)

**Comment by ufrisk** [comment]
@yaellem Thanks for making me aware of this. It used to be that you could refresh individual sub-systems, but as the number of sub-systems grew and became more interconnected I removed that ability and condensed it into the refresh functions in the C/C++ header file (also in memprocfs.py).

The net refresh constant doesn't do anything any more. Don't use it.

If requiring a full refresh of the network connections I recommend using OPT_REFRESH_ALL.

If wanting a faster refresh, but with lower quality results, you may use OPT_REFRESH_FREQ_MEM, OPT_REFRESH_FREQ_TLB, OPT_REFRESH_FREQ_MEDIUM in that order. This will force a refresh of network connections. The network connections are however sourced from internal structs (this is fast but a bit buggy and the MEDIUM will trigger a refresh of these) _AND_ the kernel pool. The kernel pool is refreshed on the SLOW frequency since it's a heavy and slow task. The pool refresh which gets triggered by your ALL refresh is probably what eats up most of your time.

I've updated the Python documentation and the vmmsharp.cs to reflect this. I know it's not the answer you wanted but it's how it is. I would think the OPT_REFRESH_FREQ_MEM, OPT_REFRESH_FREQ_TLB, OPT_REFRESH_FREQ_MEDIUM combo is probably your best shot if wanting to fetch new connections fast (if it works and isn't buggy).
