### ISSUE TITLE
Check if page is reserved ?

### ISSUE THREAD

**Issue by bin5k** [ufrisk/MemProcFS#18]
Is there a way to check if a page is reserved ?
CommitCharge and MemCommit give me positive values as shown here:

![mstsc_2019-12-23_13-10-29](https://user-images.githubusercontent.com/44826092/71360433-bd99b000-2587-11ea-8216-7581826fa4e5.png)

**Comment by ufrisk** [comment]
Your questionmask CommitCharge corresponds to the number of "Private: Commit" pages in the VAD regions.

At the moment the answer is no, I only parse out the VADs, not any sub-regions and such. Just as your other issue about this I'll have to add support for this. I'll do it, unfortunately it may take some time since I have some upcoming conference talks and also other stuff at work to focus on. But I'll add it.

**Comment by ufrisk** [comment]
I'm closing this issue since it's unlikely I'll implement this functionality in exactly this way.

It's however possible to check if a page is non-commited (sort of) by looking at the VAD map together with the PTE map and especially the extended VAD map (which is somewhat recent) to check this in an alternative way.
