### ISSUE TITLE
 No matching targets found on connected servers: localhost

### ISSUE THREAD

**Issue by nitro807** [ufrisk/MemProcFS#191]
II'm trying to flash my card, but when I do it, I get an error. The mother card detects the card, pcileech can detect the card too. I use Vivado 2023.1

ERROR: [Labtoolstcl 44-199] No matching targets found on connected servers: localhost
Resolution: If needed connect the desired target to a server and use command refresh_hw_server. Then rerun the get_hw_targets command.
ERROR: [Common 17-39] 'get_hw_targets' failed due to earlier errors.

    while executing
"get_hw_targets"
    invoked from within
"current_hw_target [get_hw_targets]"
    (file "vivado_flash.tcl" line 11)

**Comment by ufrisk** [comment]
which hardware are you trying to flash?

**Comment by nitro807** [comment]
Terminator P1, as far as I know, this is a copy of leetDMA

**Comment by ufrisk** [comment]
Please understand that this is an open source project. I've been doing this for free and giving it away for free. Some people sponsor with $2 or so here on Github, some  a bit more. LambdaConcept and the EU supplier of LeetDMA have sponsored a bit in the past as well.

Nowdays I almost get 0 in sponsorship from those since there is a lot of manufacturers selling similar boards and their main feature seems to be to not give me a single cent in sponsorship. It's how the game is played I know that and there is nothing I can do about it.

BUT i still get lots of support questions. Please understand that I'm not too keen on spending a lot of time to give support under these conditions. I.e. spending a lot of free unpaid time to give support just so that others can up their profits.

I therefore kindly ask that you contact your hardware vendor about these issues.

Thanks for understanding.
