### ISSUE TITLE
Receiving "MOUNT: Failed. Status Code: -3" when attempting to mount a .vmem

### ISSUE THREAD

**Issue by SyrupBoy76** [ufrisk/MemProcFS#192]
I'm on a MacBook Pro (M1 chip) running VMWare Fusion Pro 13 with a Windows 11 image.

I've attempted to run in both cmd and PS in admin mode and in a local admin account.

Do you know why I'm receiving this error and how I can correct it?

**Comment by ufrisk** [comment]
-3 would mean dokan driver install error.

https://github.com/dokan-dev/dokany/blob/ce8b8229ad8262f920ca8d284448c1fe10e46cae/dokan/dokan.h#L786

You could try to reinstall dokan, if the error persists there may be additional info in the system/application event log.

Please let me know how it goes.

Unfortunately I have a bit hard time checking this myself since I'd have to get myself a new mac first. I haven't been super interested since the github sponsorship program while super nice quite don't bring in that amount. But since more people are getting these I'd most likely have to get one soon regardless...

btw, are you building it yourself or are you running the x64 version on arm?

**Comment by SyrupBoy76** [comment]
Thank you so much for the support and quick response!

I originally utilized the Dokan_x64.msi, but after reading your response I then used the .exe version
[Dokan_x64.msi](https://github.com/dokan-dev/dokany/releases/download/v2.0.6.1000/Dokan_x64.msi)
[DokanSetup.exe](https://github.com/dokan-dev/dokany/releases/download/v2.0.6.1000/DokanSetup.exe)

I restarted the VM after install and I'm still receiving the same error.

I am using an Insider Preview version of Win11 (https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64); specifically the "Beta" version (Build 22598).

https://blogs.windows.com/windows-insider/2022/04/13/announcing-windows-11-insider-preview-build-22598/

**Comment by ufrisk** [comment]
I suspect there is some mismatch between x64/arm64 with regards to the driver (sys file).

In the dokan.zip file there is an ARM64 folder which contains DLLs and also the driver (and inf file for installation). Does this help in any way?

Also does the MemProcFS ARM64 release help in any way (I just uploaded it) at https://github.com/ufrisk/MemProcFS/releases/download/v5_archive/MemProcFS_files_and_binaries_v5.6.6-win_arm64-20230607.zip

I may have to get a mac myself, there have also been a few questions around pcileech on macOS M2. But I'd rather avoid it if possible due to the expense :\

**Comment by SyrupBoy76** [comment]
Please excuse my ignorance, but where do I place the files you referenced?

In my VM, I see (3) "Program Files" directories:
-Program Files
-Program Files (Arm)
-Program Files (x86)

**Comment by ufrisk** [comment]
I don't think it matter where you put the MemProcFS binaries I linked to. It's ARM binaries though.

Also I'll get a mac mini when I'm back home (in a few weeks) to further look into this. I need it for some other things as well so it should be good to test and better document things like this as well.

**Comment by ufrisk** [comment]
I got my macmini. Had the same issue with dokany -3.

To resolve (if you got the -3 error) run steps 1-4 below, otherwise run the whole thing. I don't know why dokany isn't properly installing on ARM64 but it works if you add a service manually (even after reboots).

Please let me know if this works for you and I'll update the guide about it as well. (it's good to have some more testing before I add it).


1. Download dokan.zip from https://github.com/dokan-dev/dokany/releases
2. Unzip dokan.zip
3. Install driver:
   3.1. move into dokan\ARM64\Release\Driver\sys
   3.2. right click dokan.inf and choose in the popup menu: Install
4. Start driver from administrative elevated command prompt run: `sc.exe create dokan2.sys binPath=C:\windows\system32\drivers\dokan2.sys type=kernel && sc.exe start dokan2.sys`
5. Install dokan2.dll (not required if you already got the -3 error).
   5.1 move into dokan\x64\Release
   5.2 copy dokan2.dll to C:\Windows\System32\ directory.
6. Unzip and run MemProcFS

Right now the dokan2.dll must be in the system32 directory. This will work fine as long as the x64 version is there and you run the MemProcFS x64 application. If you however want to run the ARM64 version of MemProcFS you'd need to overwrite this file. This is not ideal. I should change memprocfs.exe so that it loads the dokan2.dll from the current memprocfs directory if it's not found in system32. But I'll do this in a future release. I think it's fine for now and the 64-bit version seems to be running fine and it's quite fast. So no need for a custom ARM64 version of MemProcFS for now.

Just wish dokany would handle the ARM64 driver/service installation in their installer properly. But this is quite new still probably.

Also note that MemProcFS will not currently analyze RAM from ARM64 machines. It's something I'd have to look into as well, but it's a larger work item.


Anyway, please let me know if you have success so that I may update the Guide with the additional info.

**Comment by SyrupBoy76** [comment]
IT WORKED!

Thank you so much for the above and purchasing of the Mac Mini!
