### ISSUE TITLE
pcbRead getting nulled when calling VMMDLL_Scatter_PrepareEx

### ISSUE THREAD

**Issue by realbadidas** [ufrisk/MemProcFS#194]
Hello,
First of all, thank you for this great project.

I might misunderstand something, but why does pcbRead get nulled when calling the above mentioned function?

Here is the line of the code that causes this: https://github.com/ufrisk/MemProcFS/blob/master/vmm/vmmdll_scatter.c#L69C34-L69C34

Is this line really needed? I mean, when you execute the scatter the new value is getting overwritten anyways. This causes some minor problems in my code (that i can fix by simply copying stuff), but it is just inconvenient.

So do you think removing this line is safe?

Thank you.

**Comment by ufrisk** [comment]
I think the reasoning was that when you "prepare" the read it sets the pointer value to zero.

When the read is executed that pointer will receive the value of the actual bytes read.

If it's not zeroed in the "prepare" call it may lead to confusion by the user. If they look at the actual bytes read and they see some value not reflecting the truth (at least not until the execute call has been made.

For me it kinda makes sense that it behaves this way and that's why I designed it like that. But I don't think there will be any side effects by removing it (and building from sources yourself) if you'd rather wish to keep track of it manually.

**Comment by realbadidas** [comment]
Thanks for the reply!

Actually, it confused me that it nulled it and it took me some time to realize that the prepare method did that.

Anyways, thanks, i will just compile it to fix it.
