### ISSUE TITLE
[Question] Benchmark read speeds

### ISSUE THREAD

**Issue by Clydeston** [ufrisk/MemProcFS#200]
Hello thanks Ufrisk for the amazing tools and libs you've created. Just a quick one, are there any built in ways to perform benchmark tests for example read speeds? If not what would you suggest is the best way to get the best results? I just want to see if some scatter reads are actually faster than multiple separate reads, just wondering what the best way to check this would be.

**Comment by ufrisk** [comment]
Thanks for your kind comments :) I hope my project will be useful for you. If it indeed becomes useful please consider sponsoring with as little as $2 on my Github Sponsors page.

When reading with the NOCACHE flag scatter reading is almost always faster than multiple individual reads. The difference is very small for larger reads, but for smaller reads it's very visible.

I don't have any pre-built benchmark speed tests for this since it's heavily dependent on the workload and your target system. But if you intend to code towards the API it should be fairly easy and low effort creating a benchmark targeting your exact workload. But unfortunately not anything ready as-is.

**Comment by Clydeston** [comment]
Thanks for your reply, once I'm back working I'll be donating, really thanks for your work it's amazing
