### ISSUE TITLE
API to get winver

### ISSUE THREAD

**Issue by 0xGabriella** [ufrisk/MemProcFS#237]
hello ulf, always wishing you good luck. Just wondering if there is any API that we can use to fetch victim's PC winver? Thank you.

**Comment by ufrisk** [comment]
Hi and many thanks :)

There is already such a way. You may use the following options:

```C
// VMMDLL_OPT_WIN_VERSION_MAJOR
// VMMDLL_OPT_WIN_VERSION_MINOR
// VMMDLL_OPT_WIN_VERSION_BUILD

QWORD build = 0;
BOOL result = VMMDLL_ConfigGet(hVMM, VMMDLL_OPT_WIN_VERSION_BUILD, &build);
```

It is recommended to use the build number. The major version will return 10 even on Windows 11. This is since version number 10 is actually what Windows 11 will report.

Best wishes with your project and please let me know if you should have any more questions :)

**Comment by 0xGabriella** [comment]
Thank you for the answer ulf!. This is what i was looking for <3. Best wishes for you
