### ISSUE TITLE
VMMDLL_VfsReadW X86

### ISSUE THREAD

**Issue by zijingsh** [ufrisk/MemProcFS#239]
Hello ufrisk 
VMMDLL_VfsReadW  in x86  Calling the subroutine crashes
example:
  const size_t cbSize = 1024 * 1024 * 1024;  // выделение 1 МБ
    const size_t buffer_size = cbSize;
    BYTE* bytes = new BYTE[buffer_size];
    DWORD j = 0;
    auto nt = VMMDLL_VfsReadW(vmm_handle, (LPWSTR)L"\\misc\\procinfo\\dtb.txt", bytes, buffer_size - 1, &j, 0);

**Comment by ufrisk** [comment]
Hi, your buffer, bytes, must not be NULL. It's specified as `_In_` (and not `_In_opt_`) in the header file which means it must not be NULL when calling this function. I suspect the memory allocation will fail in your code since it's not really possible to allocate 1GB of memory on 32-bit x86 and that you then pass NULL to VMMDLL_VfsReadW which would violate the API contract.

**Comment by zijingsh** [comment]
I'll take a hard look at my code

**Comment by ufrisk** [comment]
Awesome, I think you try to allocate 1MB (from the comment) but you try to allocate 1GB instead.

Anyway, I'll be closing this issue since the issue most likely is resolved.

Best wishes with your DMA project and please let me know should you run into any more issues.
