### ISSUE TITLE
How to clear the internal cache?

### ISSUE THREAD

**Issue by Hollow-1** [ufrisk/MemProcFS#241]
Hello, ufrisk
this is the situation I face :
I need to read first pointer to locate the next read, 
and calc the pointer,then read next pointer, ...so many small reads, 
most of data to be read is together, but it keeps changing,
so, I use cache to avoid frequent access to FPGA,
but how do I clear the cache to get fresh data?

**Comment by ufrisk** [comment]
you can pass either one of the refresh options, i.e. `VMMDLL_OPT_REFRESH_*` to VMMDLL_ConfigSet or pass the VMMDLL_FLAG_NOCACHE flag to your read function.

In general for programming related questions it may be better to ask it on the discord channel https://discord.gg/BCmfBhDPXX since you'd probably get a quicker answer there.
