### ISSUE TITLE
Challenges on Ubuntu 23.10 desktop

### ISSUE THREAD

**Issue by kaarposoft** [ufrisk/MemProcFS#248]
**Thank you very much for your work on memprocfs !!!**

I have used it on windows, and it is great.

However, using memprocfs on Ubuntu 23.10 desktop is challenging.

According to [https://github.com/ufrisk/MemProcFS/wiki/_Linux](https://github.com/ufrisk/MemProcFS/wiki/_Linux)
dependencies should first be installed with
`sudo apt-get install libusb-1.0 fuse lz4`

However, on **Ubuntu 23.10 desktop** this is a **DISASTER**.

`apt-get install fuse`
will indeed install fuse version 2,
but it will also **uninstall fuse version 3**,
and **all packages depending on it**.
This renders the desktop unusable, and the distro unable to boot into graphical mode.

This is further described here:
[https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1717878](https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1717878)

May I suggest that you add a warning about this on
[https://github.com/ufrisk/MemProcFS/wiki/_Linux](https://github.com/ufrisk/MemProcFS/wiki/_Linux)

For the record, on Ubuntu 23.10 desktop this will install the required dependencies:
`sudo apt-get install libusb-1.0 libfuse2 lz4`

Please also note, that even with those changes, memprocfs will still not work on Ubuntu 23.10 desktop due to
[https://github.com/ufrisk/pdbcrust/issues/1](https://github.com/ufrisk/pdbcrust/issues/1)

**Comment by ufrisk** [comment]
I'll update the guide to warn about this.

Personally I feel it's a shitty move by the FUSE/Ubuntu breaking backwards compatibility like this not only in a way that makes things stop working but in a way that actually seems to be destroying systems.

Also it won't be possible to provide backwards-compatible binaries once I upgrade to FUSE3 I suspect, which will make people complain in the other end.

For now I'll put up the warning and recommendation to apt-get libfuse2 instead. I just need to test this first before making this change.

Huge thanks for letting me know 👍

**Comment by ufrisk** [comment]
The fix was easier than I initially though it would be. I've replaced the "fuse" package in the build instructions with "libfuse2" which for the MemProcFS usecase will work equally fine.

It has the upside that it will work fine on Ubuntu 23.10 as well.

It's quite unfortunate that the apt-get install fuse destroys the whole Ubuntu 23.10 installation. I feel I cannot take responsibility for this though. This is something that changed and sort of broke backwards compatibility. Fortunately the fix was easier than I initially thought :)

Since this issue is resolved I'm closing this issue.

Huge thanks for reporting so I was able to fix it before my instructions killed more systems.
