### ISSUE TITLE
dma help?

### ISSUE THREAD

**Issue by nosoupsforyou** [ufrisk/MemProcFS#253]
im reaching out here in hopes i can get some information on troubleshooting this dma device. ive reached out to immortal tech support and others but it appears ufrisk is the only one that has answers and helps out. if you can read this ill be happy to compensate you for your time. i recently purchased immortal warrior dma and followed the instruction video. pretty simple. my issue is when i run the test i get this error... 
"FPGA: TINY PCIe TLP algrithm auto-selected!
LcMemMap_AddRange: 0000000000000000-000000000009ffff -> 0000000000000000
LcMemMap_AddRange: 0000000000100000-00000000ffffffff -> 0000000000100000
LeechCore v2.14.2: Open Device: fpga
[CORE]     Initialization Failed. Unable to locate valid DTB. #2
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (0000016BCC57C040)."

any and all help is appreciated

**Comment by ufrisk** [comment]
I saw you found the discord.

Unfortunately I'm not able to help with all these 3rd party vendors, that generally don't contribute anything at all to my project, just leaving me to pick up the support time. Also they have custom firmware that sometimes interferes with the DMA operation.

You can have a look in the wiki to see if a memmap would help, but if that doesn't work I won't be able to help with this due to the above. https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

Thanks for understanding.
