### ISSUE TITLE
DEVICE: FAIL: unable to parse elf header MemProcFS: Failed to connect to memory acquisition device.

### ISSUE THREAD

**Issue by boredchilada** [ufrisk/MemProcFS#263]
As title states, trying to mount a .dmp file, but i keep getting this error. Using the .exe binary 

dump was made with proxmox, header seems okay

<img width="275" alt="image" src="https://github.com/ufrisk/MemProcFS/assets/82670806/fd534d08-573d-4582-a92b-07c5d091ec83">

.\MemProcFS.exe -device '..\rdp2019ransomware.dmp' -v -vv -vvv
DEVICE OPEN: file
DeviceFile_DumpInitialize: 64-bit ELF Core Dump identified.
DEVICE: FAIL: unable to parse elf header
DEVICE: ERROR: Failed opening file: '..\rdp2019ransomware.dmp'.
MemProcFS: Failed to connect to memory acquisition device.

**Comment by ufrisk** [comment]
I've only tested this ELF file format on VirtualBox since its what its creating.

Are you able to share the dump and I'll be able to take a look at it and see what I can do to get it working? If so please contact me on Twitter/Discord or at pcileech@frizk.net. If it's not possible I completely understand that as well but it would make it harder for me to add support.

**Comment by boredchilada** [comment]
expect an email from a protonmail address.

**Comment by ufrisk** [comment]
awesome, just send me the dl link and I'll take a look!

**Comment by ufrisk** [comment]
This should now be resolved.

I previously did some assumptions about the ELF core dumps which seemed only to hold for VirtualBox memory dumps.

Anyway it should work now. Huge thanks for letting me know and sharing the memory dump.

Proxmox seems to be really popular nowdays so it's great to have support for it. Thanks 💙
