### ISSUE TITLE
How do you set the interval in the configset vmmdll_opt_refresh

### ISSUE THREAD

**Issue by dolodi** [ufrisk/MemProcFS#280]
How can i set the intervals for refresh after using -norefresh and VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_FAST, 1);
VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_MEDIUM, 1);
VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_SLOW, 1);

Do i have to change 1 to the interval i want or something else ? Sorry for the dump question, but u didn’t find an answer anywhere.

**Comment by ufrisk** [comment]
Apologies for the somewhat slow answer. I get similar questions quite often and I was getting a bit tired of answering the same questions all over again so I thought it better to create a FAQ entry about it instead of directly answering here.

I hope this newly created FAQ entry at: https://github.com/ufrisk/MemProcFS/wiki/FAQ_Timing will explain your issue. Please let me know here if you feel like you're missing something or if anything is unclear with it.

Best wishes with your DMA project. If you find this open source project useful please consider sponsoring a small sum over at Github Sponsors https://github.com/sponsors/ufrisk 💖

**Comment by dolodi** [comment]
No problem, thank you very much
