### ISSUE TITLE
How to bypass "MemProcFS does not generate a minidump file for LSASS.EXE due to potential security concerns" ?

### ISSUE THREAD

**Issue by Wowhere** [ufrisk/MemProcFS#289]
How to bypass "MemProcFS does not generate a minidump file for LSASS.EXE due to potential security concerns" ?

I dont see any way to pass argument for disabling security. I think there must be a feature

**Comment by ufrisk** [comment]
This feature was removed quite some time ago since it was used in some real world attacks that did real harm.

Also I've put in many 1000's of hours into this forensic open source project. I don't wish to get all my hard work flushed down the toilet because some red teamers wants to have some quick fun, which would eventually lead to AV detection's (if I were to enable this feature) completely destroying the whole project and all the time I put into it.

There are better more specialized tools out there, such as F-Secure PhysMem2Profit.

Thanks for understanding.

**Comment by Wowhere** [comment]
Thats allright, i patched source code myself

**Comment by ufrisk** [comment]
No. It's not alright that you're actively trying to destroy my open source project. But there is nothing I can do about it.
