### ISSUE TITLE
DOKANY file system library is not installed.

### ISSUE THREAD

**Issue by harrynorthover** [ufrisk/MemProcFS#300]
I'm trying to use MemProcFS in a Windows 11 VM, running on an M1 MacBook Pro in Parallels. 

I have successfully installed Dokan, and can run the `mirror.exe` to ensure that the new drive is created ok.

However, when I try to run MemProcFS.exe, it exits immediately saying that "DOKANY file system library is not installed.". I have followed all steps in the "Manual Install" section, including creating and starting the service with Driver Signature Verification disabled. 

Any ideas on how to get this to work? 
<img width="1440" alt="Screenshot 2024-06-19 at 12 56 45 PM" src="https://github.com/ufrisk/MemProcFS/assets/150689/2ecb288f-8b52-49be-9839-b81f8ff575d8">

**Comment by harrynorthover** [comment]
Solved: I was copying the ARM64 DLL over to Win\System32. Needs the standard x64 version.

**Comment by ufrisk** [comment]
Thanks for the update and I'm glad you was able to resolve the issue.

I remember I had a similar issue when I initially tested this. I feel this ought to be resolved by the Dokany team. It can't be all that uncommon for x64 applications to be executed on ARM64 since the translation layer is really good...
