### ISSUE TITLE
Hello buddy, regarding the performance loss of version 5.11

### ISSUE THREAD

**Issue by subeoy1** [ufrisk/MemProcFS#306]
Why is the performance of the latest version lower than that of version 5.9? I found that version 5.9 performs faster and better than the latest version, which is why it has forced me to use version 5.9

**Comment by ufrisk** [comment]
In what way do you find it slower? Are you using the API, in that case which API?

Are you able to write a minimal test program that would illustrate this difference if you're using the API? Against some common windows process such as explorer.exe?

I find it strange since I'm not aware of any changes related to performance recently, but I've seen stranger things in the past so I won't rule it out. But I'd need that small test program to illustrate the difference so that I may see what's up before looking into it.

**Comment by subeoy1** [comment]
Yes, I am using your VMMDLL and VMM.H  Lee.H， As an API
ImGui::Text(Translate(u8" Current computing power::[%2.f] \n ", " Current computing power: [%2.f] \n "), ImGui::GetIO(). Framerate);
When I use version 5.9, it shows computing as 3000. Of course, this speed is based on my personal configuration.
When using version 5.11, it was only 2000-2200 About 800 performance losses were incurred
I don't know where the performance issue occurred, so I replaced it with 5.9.17
The method of performance loss in this query is too crude, so I don't know where the performance problem is. I have been studying it for a long time,

**Comment by ufrisk** [comment]
I haven't really done any changes that could affect this, at least what I'm aware of.

It would help if you could let me know in between which exact versions this issue was introduced. The 5.9 release had quite a few revisions, and there's been a 5.10 as well.

You'll find the older releases in the release archive: https://github.com/ufrisk/MemProcFS/releases/tag/v5_archive and I would at the minimum need to know in between which two specific releases your issue started to appear.

**Comment by subeoy1** [comment]
5.9.17

**Comment by ufrisk** [comment]
Is that the last good release for you or the first bad?

**Comment by ufrisk** [comment]
I haven't really changed much in those releases around it (before/after). Only thing that I could see could affect things slightly would be some internal caching. I slightly relaxed the conditions again in 5.11.4 if you wish to take a look. But I'm guessing things would be mostly the same.

**Comment by ufrisk** [comment]
it's in the releases section available for download.

**Comment by ufrisk** [comment]
Since I haven't heard anything back that the issue is still around I'm closing this issue. Please let me know if the issue persists.
