### ISSUE TITLE
How can I write to memory?

### ISSUE THREAD

**Issue by NyshMy** [ufrisk/MemProcFS#326]
I want to write to memory, but I don't know how to do it currently. Is there an example?

**Comment by NyshMy** [comment]
Can write function read integers and long integers like read function? Is there a write_type method?

**Comment by ufrisk** [comment]
It's possible to write to memory, but you don't mention your programming language so it's hard to answer.

It's probably better to ask in the coding channel on the MemProcFS server rather than on this Github issue section since it's more for reporting bugs and issues rather than asking general questions. See you over at Discord!

https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3
