### ISSUE TITLE
About offline symbol table issues...

### ISSUE THREAD

**Issue by Tokeii0** [ufrisk/MemProcFS#327]
Is there any way to get all the symbol tables for the latest versions of windows7 to windows11 24h2 that are suitable for memprocfs? Sometimes I want to use them offline, but some symbol tables are not local.

**Comment by ufrisk** [comment]
Thank You for the kind sponsorship 💖  It means a lot.

About the symbols, MemProcFS caches the most common symbols in the `info.db` sqlite database file which is included in the binary release. This database is updated after each patch tuesday and should contain the most common symbols required.

If symbols are missing and you're offline you may see where to download the symbols and where to put them if you add the command-line parameters: `-loglevel symbol:4`. This would be the normal PDB file from the microsoft symbol server.

I don't have a good collection of the symbols used, the format in the info.db database is very internal and otherwise MemProcFS just use the standard PDB's. I have a collection of several GB's of PDBs in order to create the info.db file.

**Comment by Tokeii0** [comment]
Thanks for the help. All symbol tables have been downloaded according to the contents of info.db, and the problem has been solved.

**Comment by ufrisk** [comment]
It's very nice to see this resolved your issue 👍  Thank you for letting me know.
