### ISSUE TITLE
How do I dump process memory based on process number?

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#34]
Thank you very much. Both problems have been solved.For MemProcFS, the main problem is the FTD3XX. DLL version. The version I used is 12.0.4 and the program needs 13.0.2 or above.I am very interested in your project. I am a beginner and I am not in this research direction, so I do not have the time to study, but the tools you provide are very friendly and convenient for a beginner like me, so I want to use my spare time to learn.For example, perform some memory analysis operations using the Python interface.I watched a video you posted on YouTube. You said the full memory dump is too slow, so how can you dump the memory of a particular process according to the process number?In addition, can you recommend some papers or books on memory analysis or Python API development?I do appreciate it.Thanks so much for your great support!

The DLL problem appears in the latest version of MemprocfS3.3, but everything works fine in version 3.2.

![question_4](https://user-images.githubusercontent.com/69066433/89746654-7435ab00-daed-11ea-861c-4e93dc321687.jpg)
![question_5](https://user-images.githubusercontent.com/69066433/89746659-7861c880-daed-11ea-8aa1-42cdaa7800f0.jpg)
![question_6](https://user-images.githubusercontent.com/69066433/89746673-8a436b80-daed-11ea-9b15-59fefaf1aee3.jpg)

This is the folder for version 3.3

**Comment by ufrisk** [comment]
Thanks for reporting. I'll investigate this eavning and get back to you. Python should just work; but obviously it's not in your case.

**Comment by ufrisk** [comment]
I've looked into this now. It's working perfectly on my test system with clean win10 install with latest python / anaconda and latest MemProcFS. You don't happen to run an older Windows like Windows 7; that may cause these issues since some imported symbols I recently started to use are missing and was introduced only in Windows 8.1. If you're running this on Windows 10 which version and build number are you running?

About python programming; I'm rather clueless unfortunately about good resources around this; but for memory forensics I'd say "The Art of Memory Forensics" is very good; albeit a bit old.

MemProcFS only retrieves memory required for a specific task so it's quite efficient. If you wish to get the memory dump for an individual process only you may do so, provided that you started MemProcFS with a memory dump file (i.e. not live memory from the FPGA, in that case dump to file first and then run MemProcFS on the created dump). The process minidump files are located in /name/<procname>/minidump/minidump.dmp

From Python you may access this by:
```Python
from vmmpy import *
VmmPy_Initialize(['-device', 'C:/temp/memimage.raw'])
VmmPy_Initialize_Plugins()
pid = VmmPy_PidGetFromName('explorer.exe')
print(pid)
  -> 4066
dumpinfo = VmmPy_VfsList('/pid/' + str(pid) + '/minidump/')
print(dumpinfo)
  -> {'minidump.dmp': {'f_isdir': False, 'size': 466829312}, 'readme.txt': {'f_isdir': False, 'size': 546}}
# READ 16 bytes from the file /pid/4066/minidump/minidump.dmp starting at offset zero
VmmPy_VfsRead('/pid/' + str(pid) + '/minidump/minidump.dmp', 16, 0)
  -> b'MDMP\x93\xa7\xb1d\x0b\x00\x00\x00 \x00\x00\x00'
```

**Comment by DK1998U** [comment]
i tried your code for getting "lsass.exe" minidump,but fail!
when i use MemProcFS.exe to mount the same memory image file ,i got  "lsass.exe" minidump

### fail with python code 
![fail_with_python](https://user-images.githubusercontent.com/50914781/108796001-a955a680-75c2-11eb-8c21-969b49939d31.jpg)

### success_with_memprocFs mount
![success_with_memprocFs exe](https://user-images.githubusercontent.com/50914781/108796020-b83c5900-75c2-11eb-8bfa-adf148c28ca8.jpg)

**Comment by DK1998U** [comment]
![fail_with_python2](https://user-images.githubusercontent.com/50914781/108797053-3a2d8180-75c5-11eb-990b-1e9a93b4f5c5.jpg)
code execute poc

**Comment by ufrisk** [comment]
@DK1998U I tried this and it's working with same windows version. Is your PC running Python connected to the Internet?

Minidump may download symbols from the microsoft server if this is the first time doing this and will fail if this is not possible.

**Comment by DK1998U** [comment]
maybe,there is something wrong with my network connection,it work this time

one more question, is that necessary to call VmmPy_Close() when i don't want to use MemProcFS interface

**Comment by DK1998U** [comment]
it seems that after VmmPy_Initialize() function executed the initialization is not complete

**Comment by ufrisk** [comment]
@DK1998U It's completing in the background for faster startup times. If you require it to be complete at startup please add extra parameter `-waitinitialize` to VmmPy_Initialize() call.
