### ISSUE TITLE
Speedtest close in seconds

### ISSUE THREAD

**Issue by Stan0585** [ufrisk/MemProcFS#344]

**Comment by Stan0585** [comment]
![image](https://github.com/user-attachments/assets/48e9cffb-2ac0-412b-90c2-6de0e98e421b)
I'm getting this error. I apologize I'm new to this.

**Comment by ufrisk** [comment]
That is a 3rd party speed test not related to the project as such. But it's a pretty common one.

It says the dll is missing, maybe add it?

Anyway, I'll be closing this issue since it's not really an issue with the MemProcFS project as such, more of general help and guidance. It's probably better to ask around in the Discord server if you haven't already resolved it.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
