### ISSUE TITLE
Failed to refresh MemProcFS - aborting 

### ISSUE THREAD

**Issue by Avapt** [ufrisk/MemProcFS#353]
I've run the memproc.exe -device FPGA -v -vv command and after a while, I get  " Failed to refresh MemProcFS ". Does anyone know how to fix it? This has affected me with different scenarios when trying to use my card.

**Comment by ufrisk** [comment]
it's likely you have to use a memmap: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

I'm closing this issue since the issues section is for reporting bugs in memprocfs rather than general guidance/help. For various connection issues the Discord server is the better choice.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
