### ISSUE TITLE
VMMDLL_MemReadEx performance question

### ISSUE THREAD

**Issue by false** [ufrisk/MemProcFS#45]
Hi,

I need a small confirmation/information, as I would like to read a lot of data in a loop.

Could you please confirm that VMMDLL_MemReadEx automaticly reads a minimum of exactly 0x1000 bytes ?
Meaning in term of   TLPs,  resources,  performance, timings it is  EXACTLY the same to call
- 200B: VMMDLL_MemReadEx(...cb: 0x200 bytes ..) and 1000B: VMMDLL_MemReadEx(...cb: 0x1000 bytes ...)

Which means in the end there is absolutely ZERO advantage to try to read less data >= 0x1000 bytes, right ?

Thanks :-)

**Comment by ufrisk** [comment]
correct. there is zero performance reason to read less than 0x1000 bytes.

this is done to simplify code and ease caching. also, in reality there is no measurable difference in reading smaller values since the read of such a small amount is almost entirely based on latency (round trip time for usb write to write the read tlp to the device + time for usb read to read the result from the device). it's a magnitude larger than actual transfer time. it makes no sense for me to read less bytes from the tlp layer either unless you read larger chunks of memory in one go.

it's possible to read smaller amounts of memory with the readscatter function though it you really really want to do it. but in reality there won't be a performance benefit of this when reading below 4 or so memory addresses in one go.

**Comment by ufrisk** [comment]
But what will give you a huge performance boost is to read multiple memory addresses (in different pages) at the same time - i.e. use the ReadScatter function.
