### ISSUE TITLE
Build documentation, and hand holding surrounding examples like vmm_example.c

### ISSUE THREAD

**Issue by rlewkowicz** [ufrisk/MemProcFS#51]
I wanted to come here with solutions in case any one else has similar issues, and then leave this open for documentation improvements. I was looking to just compile and run vmm_example.c

So I'm not a dumb guy, I'm just not familiar with the tool chain and my os preference is linux. My goodness this whole experience was rough. Part of it is that I need to go get fisher price my first visual studio, but the tool chain doesn't even have like native help docs as far as I can tell. I feel like all the tools and arguments are SUPER clunky. 

There has to be a better way then this (which worked):

Quick preface if you're here looking for help. You'll need the windows 10 SDK and then if you can't find something you can search for it: `name:=exact_file_name` Your paths below will be similar but different based on which packages you installed

```
$Env:INCLUDE = "C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt;C:\Users\Ryan\Documents\MemProcFS\includes"

 C:\Program` Files` `(x86`)\Microsoft` Visual` Studio\2019\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe /EHsc .\vmmdll_example.c "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\Uuid.Lib" "C:\Users\Ryan\Documents\MemProcFS\includes\lib64\leechcore.lib" "C:\Users\Ryan\Documents\MemProcFS\includes\lib64\vmm.lib" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\x64\libcmt.lib" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\x64\oldnames.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\kernel32.Lib" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\x64\libvcruntime.lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64\libucrt.lib" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\x64\msvcrt.lib" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.16.27023\lib\onecore\x64\msvcrtd.lib" /link /subsystem:console
```

**Comment by ufrisk** [comment]
I cannot do much about documentation not being included; that's a Microsoft issue unfortunately.

Also; most people tend to do this inside the GUI; which handles most of the stuff in a convenient way.

If building via the command prompt you can use the "msbuild";
1) start `x64 Native Tools Command Prompt for VS 2019` in start menu to get the environment
2) run `MSBuild _path_to_memprocfs_\MemProcFS.sln /t:Rebuild /property:Configuration=Release /property:Platform=x64`

I can add that you need the Windows 10 SDK in the build instructions if that would help. This should be possible to install in the Visual Studio Installer. And also the msbuild if that would make things better too?

It's very good to get feedback like this; I guess not many Windows users actually build from source; even not the ones that use my project in a C/C++ setting since they most often would just include my pre-built binaries. Those that actually build tend to be very proficient and miss things like this.

**Comment by rlewkowicz** [comment]
I couldn't figure out how to do it in the gui. I could to ctrl+f7 and it would spit out an .obj but I couldn't figure out how to execute that. Then you can try to cl that, but if your target in the gui isn't right you'll get errors with _getch().  I did eventually figure  out you could run debug and it would work if you copied the pre compiled binaries. 

I think you're right though, there's not much you can do for people that don't have domain knowledge.

**Comment by ufrisk** [comment]
did you manage to build with msbuild and visual studio command prompt I suggested?

also it should build by pressing "F7" inside visual studio; I think you may need to have at least one Win10 SDK installed from the Visual Studio Installer tho. Also you may need to have the LeechCore project from my Github placed alongside MemProcFS.
