### ISSUE TITLE
VmmProc: Unable to auto-identify operating system for PROC file system mount.

### ISSUE THREAD

**Issue by JamesFirth2020** [ufrisk/MemProcFS#53]
When I try running this it fails immediately with the message:
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
MOUNT: INFO: PROC file system not mounted.

Adding a numerical value after the -cr3 switch does allow some progress but I'm not sure what value to input here and it never expands the files as per the youtube. Python 37 is in the python folder, VB is already installed and I've installed Dokan. Not trying to live acquire, just open a previous capture. Running up to date Windows 10 and am otherwise stuck.

**Comment by ufrisk** [comment]
Thanks for reporting this, this happens now and then and I try to do my best to fix it.

Fastest and easiest way for me to be able to look into this would be to take a look at the memory dump if possible. If possible could you please put it on google drive or somewhere similar and email me the link to pcileech@frizk.net

**Comment by ufrisk** [comment]
would it be possible for me to take a look at a faulting memory image with this error; or does it contain sensitive information?

It's very hard / impossible for me fix this without being able to replicate the issue unfortunately.

If it's not possible for me to take a look at the memory image it's totally understandable but it also unfortunately means I won't be able to fix this issue. Regardless it would be nice to know.

**Comment by JamesFirth2020** [comment]
Hi, I can't really send you the image - the problem I had initially is that it's a bad capture I think - I used winpmem and it's not the first time it's caused me issues, but the thing won't even open in volatility, it's just all sorts of wrong, so I think on this occasion it's the file that's a problem.

My current issue is pykatz not working, even though I have python 3.9 installed, as path default and all dependencies installed, yet it insists it is not installed....

**Comment by ufrisk** [comment]
alright then, thanks for the response. I'll close this issue then and assume it was due to a broken memory dump. Please let me know if you should run into similar issue in the future.

About the pypykatz; you'll have to install it - either from within MemProcFS (it will download it automatically) - if that fails you may copy it manually and place it in the plugins folder as instructions from the plugin project: https://github.com/ufrisk/MemProcFS-plugins The python files should go into `<MemProcFS-Dir>\plugins\pym_pypykatz`

You'll also have to install the dependencies with pip as described in the plugin project.

Good Luck and a happy new 2021 👍

**Comment by rauramgom** [comment]
Hey, same problem here.

When I try to run MemProc over a raw ram image it returns the following output:

[INFODB]   AGEGUID=EF9A48AFA50FF07C616585BB019195361 va=0xfffff80039ca2000
[INFODB]   INIT: SUCCESS: va=0xfffff80039ca2000
[SYMBOL]   Initialization of debug symbol .pdb functionality completed
[SYMBOL]   [ srv*C:\Users\<XXXX>\Downloads\MemProcFS_files_and_binaries_v5.3.2-win_x64-20230215\Symbols*https://msdl.microsoft.com/download/symbols ]
[SYMBOL]   Initialized symbol subsystem (Microsoft).
[INFODB]   Missing TypeChildOffset(Dynamic): _DISPATCHER_HEADER.SignalState
[INFODB]   Missing TypeChildOffset(Dynamic): _KPROCESS.DirectoryTableBase
[INFODB]   Missing TypeChildOffset(Dynamic): _KPROCESS.UserDirectoryTableBase
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.ImageFileName
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.UniqueProcessId
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.InheritedFromUniqueProcessId
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.ActiveProcessLinks
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.Peb
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.SeAuditProcessCreationInfo
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.VadRoot
[INFODB]   Missing TypeChildOffset(Dynamic): _EPROCESS.ObjectTable
[INFODB]   Missing TypeSize(Dynamic): nt!_EPROCESS
[PROCESS]  OK: TRUE
[PROCESS]      PID:  2e0 PPID: 3e0 STAT: 004 DTB:  028 DTBU: 278 NAME: 450 PEB: 3f8
[PROCESS]      FLnk: 2e8 BLnk: 004 oMax: 858 SeAu: 468 VadR: 628 ObjT: 418 WoW: 428
[PROCESS]  SYSTEM DTB: 00000000001aa000 EPROCESS: ffffe50ed7660040
[PROCESS]     # STATE  PID      DTB          EPROCESS         PEB          NAME
[PROCESS]  EPROCESS_ENUMERATE END:   [time=547ms scatter=0x3 pages=0x18]
[CORE]     Initialization Failed. Unable to walk EPROCESS. #5
VmmProc: Unable to auto-identify operating system for PROC file system mount.
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.
[CORE]     Failed to initialize.

The image belongs to a Win10 (not 100% sure but..) but I have no other option to test it, since Volatility does not return valid output from there

**Comment by rauramgom** [comment]
Update: image may have been collected with dumpit

**Comment by ufrisk** [comment]
@rauramgom my best guess is that this memory dump would somehow be corrupt and that's why you're having issues.

Now, there may be issues with MemProcFS as well, but in order for me to look into it I'd need access to the problematic memory dump. If it's possible to share it please zip it and upload it somewhere and send the download link to me at pcileech@frizk.net

If it's not possible for you to share it I totally understand, but it would also be very hard / impossible for me to look closer into what's causing the issue.
