### ISSUE TITLE
Any chance for Linux Support

### ISSUE THREAD

**Issue by xSalice** [ufrisk/MemProcFS#58]
Any chance for us to deploy and use this on a linux system like Ubuntu later? Is that on a roadmap somewhere?

**Comment by ufrisk** [comment]
There are two aspects to Linux support

1) Analyzing Linux systems.

2) Deploying on linux and still analyze Windows systems.

---

I assume you mean the latter; but for completioness I'll answer the first one as well. No - MemProcFS is not likely to support analyzing Linux systems. I feel that this should be done as a separate, but similar product. It's not likely due to time constraints though; but maybe in the future.

---

I have plans for adding the ability for the backend LeechCore library (which already works on Linux) to be able to connect to remote Windows machines to access live Hyper-V physical memory as an example. I'm not willing to commit when but probably later this year at the earliest. This would be about physical memory access only though.


About doing memory analysis of Windows systems on Ubuntu with MemProcFS; I'd say it's not likely. It's a lot of work porting this to Linux even though it's completely realistic.

Please understand that this is a hobby project of mine; and as such my time is limited since I have a day job as well. If I had the time and there was a need for it sure - but that would imply serious funding to make it worthwile.

Due to time constraints I have to prioritize. I'm focusing on new features and analysis capabilities pushing memory forensics forward rather than porting to multiple platforms. Best shot right now would probably to be running a Windows VM or something like that. I have plans for a new better renovated MemProcFS Python API on python pip though; but it would still be Windows only unfortunately.

**Comment by xSalice** [comment]
Thanks for the input :). Answer my question thoroughly in regards to 2!
