### ISSUE TITLE
Is it difficult to support physical memory analysis for Linux

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#68]
Is it difficult to support physical memory analysis for Linux
The current analysis experience on Windows is great, so I would like to ask if Linux physical memory analysis is difficult.

**Comment by ufrisk** [comment]
Hi, and thank you for this question :)

This depends a bit on what you mean. Since version 4.0 / 4.1 I do support memory analysis of Windows memory on Linux in a fairly feature complete way. It even runs well on Raspberry Pi 4.

---

Supporting analysis of Linux memory would be a very big job unfortunately. Exactly how big would depend on the number of features. A more basic version would be easier than implementing all what MemProcFS for Windows currently support. A more feature complete implementation is easily in the multiple 1000-hour range. A useful implementation with decent process support would still easily be many 100's of hours.

A big issue with Linux is that it's so diverse, which makes it a harder to support in a really good way compared to Windows.

With me having a day job as well I unfortunately just don't see how I'll find the time to make such a big commitment time wise. Supporting and improving upon the DMA side of things and also the Windows memory analysis sucks up pretty much all spare time as-is already.

With this being said I might start looking into some aspects of this; supporting Windows WSL a bit more than I currently do. That may longer term lead to full Linux support since there are some synergies around this.

**Comment by teatreee** [comment]
Thank you for your reply

**Comment by ufrisk** [comment]
I'm closing this issue due to old age. I probably never will do Linux analysis. This is due to lack of time with this being a side project for me besides my normal work.

Thank you for understanding.
