### ISSUE TITLE
How to use the MemProcFS file system to quickly analyze the memory of the remote computer?

### ISSUE THREAD

**Issue by teatreee** [ufrisk/MemProcFS#69]
1.I'm the lab environment.
2.I want to know how to implement the simulation environment running LeeChagent
3.I saw in your blog that In lab environments it's possible to execute LeechAgent in an unauthenticated insecure mode which does not rely on Active Directory for authentication.
![as](https://user-images.githubusercontent.com/69066433/123810591-1d170f80-d925-11eb-86ec-c8040fe5fdfd.jpg)

**Comment by ufrisk** [comment]
awesome :) it's working fairly well for me now; but there may be some glitches still; I'll hopefully be looking into a refresh of it in the not too distant future.

The connection string from MemProcFS would be: `MemProcFS.exe -device pmem -remote rpc://insecure:192.168.1.1`  (note the insecure instead of of your 1st occurrence of the IP address.

You'd also need to have the leechagent started on the remote computer as elevated admin (required for it to load the winpmem) and also have the winpmem alongside it. Also it must not be blocked in the remote computer firewall (a special opening for port 28493 may be needed)

Please let me know if you get it to work.

**Comment by teatreee** [comment]
I have installed it with administrator privileges but it still cannot be linked.I don't know what went wrong. 
remote computer:
![install](https://user-images.githubusercontent.com/69066433/123968185-97a96300-d9e9-11eb-8dc9-544efbfcf44e.jpg)
![att_winpmem_64](https://user-images.githubusercontent.com/69066433/123968202-9bd58080-d9e9-11eb-9c27-fb2286117907.jpg)
![28473](https://user-images.githubusercontent.com/69066433/123968218-9f690780-d9e9-11eb-8fb3-fd2c32988c81.jpg)
My computer:
![remoteinstall](https://user-images.githubusercontent.com/69066433/123968384-c1628a00-d9e9-11eb-9e06-63bd905d8c90.jpg)
![memprocfs-remote](https://user-images.githubusercontent.com/69066433/123968399-c45d7a80-d9e9-11eb-9b19-e23d477e6fbb.jpg)

**Comment by ufrisk** [comment]
when installing the agent as a service I don't allow it to run in the insecure mode. I didn't want people to start using it as a backdoor for various red-team activities so that it would start being detected by AVs. In service mode it's only possible to connect to it if your're running in an active directory (I believe this check is missing from the install - it's something I should add as well). Please let me know if you're running in an active directory?

If not you'll have to uninstalle the leechagent. Then start it with `leechagent.exe -insecure -interactive` and it will work.

![leechagent](https://user-images.githubusercontent.com/18221464/123970061-1803a000-d9b9-11eb-9b46-1ebcbeb4e11c.png)

I also see you have the att_winpmem.sys. This is a bit older version of winpmem; it's very likely to bluescreen more recent windows versions. You can get a newer one from here: https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM

I have this a little bit documented at: https://github.com/ufrisk/LeechCore/wiki/Device_Remote and https://github.com/ufrisk/LeechCore/wiki/Device_WinPMEM - but as I mentioned previously it's a bit badly documented and I'll try to update it a bit later this summer :)

Also long term plan is to add some other authentication to the agent than just "active directory kerberos" and "insecure". Possibly certificate based and/or password based. 

Please let me know if you have better luck with it now.

**Comment by teatreee** [comment]
It's amazing that it's working now. I'm not running under Active Directory.

**Comment by ufrisk** [comment]
Awesome that you got it to work :) Thanks for letting me know.

The Agent with WinPMem and also the Hyper-V LiveCloudKd is very nice in lab environments :) I'll do a bit of a refresh around this and also record some demo videos a bit later this fall (if everything goes to plan). Please let me know if you should run into anything that you feel is missing and that I should add.

**Comment by ufrisk** [comment]
I'm closing this issue since it's now working. Please let me know if you should run into anything else around this or if you come up with anything you feel is missing. Good Luck :)
