### ISSUE TITLE
Redundant struct size

### ISSUE THREAD

**Issue by tathanhdinh** [ufrisk/MemProcFS#7]
Hello,

In this function https://github.com/ufrisk/MemProcFS/blob/4a1217906c0bc5a637070c7c21fc81c9c2ea0ab6/vmm/vmmdll.h#L529-L530

IMHO, the parameter `_In_ PSIZE_T pcbProcessInformation` isn't needed, that's because the size of filled data is statically always `sizeof(VMMDLL_PROCESS_INFORMATION)`: we don't need to call the function (with `pProcessInformation` as NULL) to get how many bytes of data will be filled.

Indeed, the implementation:

https://github.com/ufrisk/MemProcFS/blob/4a1217906c0bc5a637070c7c21fc81c9c2ea0ab6/vmm/vmmdll.c#L880-L883

(In reading the code, I understand the technique of passing NULL first to get the needed size of allocated data, but in this case it may not necessary?)

**Comment by ufrisk** [comment]
Maybe the API is a bit over-engineered.

The reasoning behind that design choice is that this makes it easier to expand the returned info-struct in the future without the risk of breaking stuff.

Also since it's the external API I do not wish to make changes to it unless it's really necessary.

I may however change this if I make some "breaking" API changes some time in the future.

**Comment by tathanhdinh** [comment]
Hello @ufrisk,

Thanks for the response

> ...since it's the external API I do not wish to make changes to it unless it's really necessary.

This is fine for me.

**Comment by ufrisk** [comment]
I've decided to leave this as-is so that I do not have to break API backwards compatibility. It's not an error per-se even though one could argue the API is over-engineered. Huge thanks for this and your other issues reported.
