### ISSUE TITLE
[32-bit linux support requested] - crash issue on 32-bit raspbian

### ISSUE THREAD

**Issue by false** [ufrisk/MemProcFS#70]
Hi,

I am experiencing a crash issue with MemProcFS 4.1, on the init step ; It seems related to memory management.
System is raspbian v10, last official stable release from January 2021 iirc.

The crash is : malloc.c:4028: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
The backtrace changes, but I tracked it down to vmm.c:VmmTlbPrefetch : If I comment/remove "VmmCacheReserveReturn(ppObMEMs[i]);" or (/and) LcReadScatter(ctxMain->hLC, cTlbs, ppMEMs); , everything seems to work normal, windows , processes etc are detected, I can read memory ; But then I suppose I will have big memory leaks. I tried different tactics but didn't manage to fix it. 

Any idea of what the cause could be ?

ty :-)

**Comment by ufrisk** [comment]
Thanks for reporting. This is not good. And yeah those functions shouldn't be commented out.

Just making sure this is the 64-bit version of Raspbian we're talking about here. I don't officially support MemProcFS on 32-bit OS.

I'll assume you're on the 64-bit version. I also assume you're using the FPGA against a live system.

If you're creating a memory dump with PCILeech and then use MemProcFS on that memory dump will the crash still happen? If so would you be able to share this memory dump with me so that I may look into this.

**Comment by false** [comment]
No I was testing it on a raspberry pi 2, so it's 32 bits. I though about the available ram issue indeed (raspberry pi 2 ram is only 1GB), but I have around 700 MB available, and a 1GB swap file, and as pointed out when I commented this line, every functionalities worked. But ofc valgrind and a simple htop shown a memory leak related to this commented line (>-OBx).
This is why I though I would try to make it work, it seemed so close to be compatible with this platform.

Not really meant to be in this crash issue topic ; but did you "validate" it on a raspberry pi 4 2GB/4GB or 8GB ?

**Comment by ufrisk** [comment]
I haven't tried this on 32-bit. I would expect there to be lots of issues mainly related to different sized pointers but also around other things. It's interesting (and encouraging) that you got it to work somewhat on 32-bit RPi.

Since 32-bit isn't supported I'll put this down as a feature request instead of a bug.

I've tested this on RPi4 with 64-bit Raspian OS. I have the 8GB version, but I have no reason to see why the 4GB should't work equally well (it was sold out tho so the 8GB version it was for me) and probably the 2GB version will work as well (albeit mbe a bit slower) if running the 64-bit version of Raspbian.

**Comment by ufrisk** [comment]
Update> I'll most probably look into this a bit closer in the next few months since I now also have a use case for running this on 32-bit myself. I'm not sure how much work it's involved though and it may very well be that I drop this. But at least I'll be looking into it now :)

**Comment by ufrisk** [comment]
I have looked more into this.

I'm treating pointers as 64-bit addresses pretty much everywhere; there are lots of crashes when compiling to 32-bit. It would be a huge undertaking in porting this to a 32-bit architecture.

I've decided against this. It's just not worth the effort for me especially when even the RPi nowdays is 64-bit capable. MemProcFS is working really well on the RPi4.

Please understand that I'm not keen on spending hundreds of hours in unpaid time in porting and debugging crashes just so that people may avoid purchasing a $50 hardware.

Thanks for letting me know about it though. It was good for me to look into the feasibility of this. I've thought about it for some time but now I know it's just a too big job for it to be worth for me at least for this moment.

Thanks for understanding.

**Comment by ufrisk** [comment]
Update: I decided to make a 2nd attempt to look some more into this and it seems like I got 32-bit support working.

You'd have to build from source; but it should work fine at least on Raspberry PI 3 (my test system).

You will have to build the leechcore library first; and then memprocfs. Also copy the info.db file from the binary release.

Good Luck :)
