### ISSUE TITLE
Specify scatter_read ranges in python api

### ISSUE THREAD

**Issue by FlameSky-S** [ufrisk/MemProcFS#85]
Hi,
I'm using python api to read many scattered bytes frequently. Currently i'm using the `process.memory.read` function because the `process.memory.read_scatter` function seem to be an overkill as it reads much more bytes than I need (no two reads are within the rage of 4096 bytes). 
I read in the wiki that the C api provides a `VMMDLL_Scatter_PrepareEx` function which can specify ranges of scatter reads. Is there a python equivalent that is not documneted? If not, are you planning on implementing a similar feature for the python api?
In my case, should I use `read_scatter` or `read` to achieve best performance?

**Comment by ufrisk** [comment]
Hi,

I haven't added this to Python yet. My plan was to wait for people to start using the C/C++ API get some comments and make some adjustments to it before adding it to Python as well.

The new C/C++ API actually behind the scenes read 4096 full pages as well right now, but it does some other nice things such as removing duplicates. FPGA access is quite latency bound so it's more that the number of calls (which are greatly reduced by the API) matters rather than the actual size (which still matters, but to a much lesser degree).

If really required I might look into making some additional optimizations in the C/C++ implementation. (hopefully without changing the actual API).

But plan is to add Python support some time at end of January unless something unforeseen happens. If I haven't done it by then please ping me again here.

**Comment by FlameSky-S** [comment]
Thank you for your answer, it helps a lot!

**Comment by ufrisk** [comment]
I looked a bit more into this. I hope to release an update including the Python API super early in January. I'll ping you here once it's done :)

**Comment by ufrisk** [comment]
Python API should now be in the most recent update. If you're using the python pip package you will have to upgrade it.

You'll find info and documentation at: https://github.com/ufrisk/MemProcFS/wiki/API_Python_ScatterMemory

Please let me know if anything should be unclear or should be improved upon. Also please let me know if you wish for any additional features.

Since this issue should now be resolved I'm closing the issue. Many thanks for the suggestion about this.
