### ISSUE TITLE
Some differences on the results of the forensic module depending on how to specify options

### ISSUE THREAD

**Issue by herosi** [ufrisk/MemProcFS#95]
This is a small impact but I want to let you know that the results of the forensic module are slightly different on each method below.

- Method 1
`.\MemProcFS.exe -device physmem.raw -pagefile0 pagefile.sys -pagefile1 swapfile.sys -mount m
`

After mounting the image, go to forensic folder and change the value 0 to 1 on forensic_enable.txt.

- Method 2
`.\MemProcFS.exe -device physmem.raw -pagefile0 pagefile.sys -pagefile1 swapfile.sys -mount n -forensic 4
`

![pic1](https://user-images.githubusercontent.com/20717881/165042321-13d0a8d5-e3d6-44f6-9c60-6182b41e2466.png)
![pic2](https://user-images.githubusercontent.com/20717881/165042323-7af11737-64f6-4e44-a6e6-7031b545c54b.png)
![pic3](https://user-images.githubusercontent.com/20717881/165042327-1c8556ae-b5a4-4aba-b257-cbc5bc8889a4.png)
![pic4](https://user-images.githubusercontent.com/20717881/165042329-3a01c99f-93bf-4a7d-a6e7-1587144943d0.png)

I think they should match each other because they come from the same memory image.
I tested on MemProcFs 4.7.9.

**Comment by ufrisk** [comment]
Thanks for reporting this. I've been aware of the issue since before, but I'll look into it again and try to fix it.

Issue is due to multi-threading. Threads on different CPU cores will be scheduled by the OS differently and cause differences in output. This is due to:
1) lack of sufficient sorting of some components, I'll have to look into adding sorting in some additional places.
2) cache evictions - sometimes data is prefetched into a cache for performance reasons, and then analysis only happens on cached data. Sometimes under heavy load some of this data may be evicted before processing is complete - resulting in some data loss. I agree that this is quite bad, even though overall results are still better than the results of many other tools. I'll look into this one as well. Maybe it will be that I only fix it for file analysis (i.e. a no-fix for analysis of live memory - but memory should change so quickly there anyway so it won't be an issue).

**Comment by herosi** [comment]
Thanks for the answer. I think you don't need to fix No. 1. since the performance is also important and we do not loose any information. We can sort the result if it is necessary.

**Comment by ufrisk** [comment]
Hopefully the v4.7.10 release which I just published should have greater consistency when starting MemProcFS with the `-forensic` parameter (strictly target memory needs to be local (i.e. non-remote) static (i.e. not live)). This should always be the case when doing memory dump analysis for forensic purposes.

If enabling forensics mode after start-up some processing have already taken place in the more efficient way which will still mess up results. So for good results MemProcFS must be started with the `-forensic` parameter.

Please let me know if this works fine for you as well.

**Comment by herosi** [comment]
It looks great. Thank you for the amazing release. I will always use -forensic option when I analyze a static memory image.
