### ISSUE TITLE
Registry data under HKU are not listed while parsing Win11 memory image.

### ISSUE THREAD

**Issue by unk0unk0unk0** [ufrisk/MemProcFS#96]
Many thanks for your awesome project.

I found that Registry data under HKU are not listed while parsing Win11 memory images with MemProcFs 4.7.10.
At that time, ORPHAN folder under "\registry\HKU" are also empty. However, the data corresponding to HKU seems to be listed in the ORPHAN folder of "unknown" user folder under "\registry\by-hive".

![Untitled](https://user-images.githubusercontent.com/51192060/165696764-68b9d16d-a7bf-41fd-938c-8a93ab3f57eb.jpg)
![unknown_folder](https://user-images.githubusercontent.com/51192060/165696657-4c48e348-31c6-4a5d-8a51-6c20c2b3d446.jpg)

I confirmed this issue on multiple memory images. And this is not occur while parsing Win10 memory images.
It might be a bug on parsing registry data on Win11 memory images.

If you need the memory image, I can provide it.

**Comment by ufrisk** [comment]
It's working for me on some of the Windows 11 images, so I don't think it's a general bug. But maybe Microsoft changed something how things work on Windows 11 so things break more easily.

Having access to the memory image would be super nice if you're able to send me a twitter DM with the download link :)

**Comment by unk0unk0unk0** [comment]
Thank you for the quick answer. I have sent the download link on twitter.

**Comment by ufrisk** [comment]
I hope this should be mostly resolved now in the 4.7.13 version. Please let me know how it works out for you.

**Comment by unk0unk0unk0** [comment]
4.7.13 works well on my environment. The registry data for the user "localadmin" has been found under the folder "\registry\HKU" by parsing the memory image. I really appreciate your excellent work.

On the other hand, I found the bellow folders in "\registry\by-hive" while parsing the same memory image.

- 0xffffa9048cd7f000-unknown-rs_localadmin_ntuser.dat
- 0xffffa9048cd8a000-UsrClassdat-USER_S-1-5-21-969434767-4224128662-244244299-1001_Classes

The upper one seems to be the ntuser registry hive for the user localadmin, and the bottom one seems to be the UsrClass registry hive for the same user. It wouuld be better if these had the same naming convention.

**Comment by ufrisk** [comment]
I'm glad to see it's working :)

About it not showing the SID. Reason why it wasn't working in the first place is that some key memory pages have been paged out and are unavailable. I guess you also have some smear/drift even if you have the pagefile since it does not seems like it was taken at the very same instant (VM snapshot) rather than a few seconds/minutes apart.

Anyway retrieving the SID would require MemProcFS to parse the whole hive - which is somewhat performance intense. In forensic mode this isn't really an issue, but I rely heavily on the hive lists for other performance critical stuff and I'd rather not slow down everything just to retrieve the SID. And also I don't wish to change the name on the fly after the SID has been retrieved.

I think for now it will stay as-is if it's not a huge thing. I could possibly add it if the forensic mode has been started when the initial hive parsing occurs if it's really important.

**Comment by unk0unk0unk0** [comment]
Thank you for the detailed explanation. And many thanks for your great enhancement.
