### ISSUE TITLE
findevil seems to be unable to find RWX memory area in some cases

### ISSUE THREAD

**Issue by unk0unk0unk0** [ufrisk/MemProcFS#98]
While parsing a certain memory image, findevil did not display the memory area in RWX mode. And I find the same issue by parsing another memory image.

I will send the download link for the memory image on twitter.
By parsing the image with MemProcFs 4.7.13, the memory area 0x7f70000 in the process ID 5944 is set as the protection mode RWX. However, findevil does not show the area.

At that time, I mounted the image with the following command-line.

`MemProcFS.exe -device \path\to\physmem.raw -pagefile0 \path\to\pagefile.sys -pagefile1 \path\to\swapfile.sys -forensic 4`

**Comment by ufrisk** [comment]
Thank You for reporting this.

I looked into it very quickly. It seems like it's a 32-bit process (wow64). I just haven't gotten around implementing FindEvil for 32-bit yet.

I realize that the guide page at https://github.com/ufrisk/MemProcFS/wiki/FS_FindEvil doesn't tell that explicitly. It only tells that FindEvil isn't implemented on 32-bit Windows. Short term I'll see to it that I update the guide page to reflect this as well.

Longer term I'll have to add this feature to 32-bit processes as well.

**Comment by ufrisk** [comment]
My earlier answer was a bit too hasty.

I would need some more information on the browser-up.exe-5944 process to be able to pinpoint this better and possibly add it to the FindEvil functionality.

When checking `M:\name\browser-up.exe-5944\memmap\vad-v\_vad-v.txt` I see very few active memory pages (pages that are loaded into the process by the current page tables executable on the CPU). Almost all pages are backed by prototype pages (pages of images backed by kernel not yet loaded into process memory since no thread have been accessing them). This few active pages in core images such as ntdll and the wow64 subsystem is very suspicious.

Furthermore, all threads are in WAIT state.
```
   #    PID     TID          ETHREAD Status/Prio   ExitSt     StartAddress   InstructionPtr                 TEB          StackBase           StackPtr         StackLimit  CreateTime                 ExitTime                
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                
0000   5944    5956 ffffe78c738d3080  5  0  8  8        0 ffffc1042cc028a0         77871cf3 --           cbf000 :           a2fd20 >           a2ec28 >           a28000 [2022-05-06 07:46:44 UTC ::                     ***]
0001   5944    6352 ffffe78c72bec080  5  0  8  8        0     7ffd850e4830         77871cf3 --           ce3000 :           bffd20 >           bfe9a8 >           bf8000 [2022-05-06 07:48:14 UTC ::                     ***]
0002   5944    6612 ffffe78c72c0b080  5  0  8  8        0     7ffd850e4830                0 --           ccb000 :                0 >                0 >                0 [2022-05-06 07:46:50 UTC ::                     ***]
0003   5944    6624 ffffe78c7050a080  5  0  8  8        0     7ffd850e4830     7ffd85186f14 --           cd7000 :          47ffd20 >          47fdfc8 >          47f8000 [2022-05-06 07:46:50 UTC ::                     ***]
0004   5944    6628 ffffe78c72b6d080  5  0  8  8        0     7ffd850e4830     7ffd85186f14 --           cdb000 :          485fd20 >          485e5e8 >          4858000 [2022-05-06 07:46:50 UTC ::                     ***]
0005   5944    6632 ffffe78c737de0c0  5  0  8  8        0     7ffd850e4830         77871cf3 --           cdf000 :          800fd20 >          800f0a8 >          8008000 [2022-05-06 07:46:51 UTC ::                     ***]

```


Furthermore, the primary process thread is stuck at:
```
0:000> ~0 k
 # Child-SP          RetAddr               Call Site
00 00000000`00a2ec28 00000000`77871bd2     wow64cpu!CpupSyscallStub+0x13
01 00000000`00a2ec30 00000000`77871d75     wow64cpu!Thunk2ArgNSpNSpReloadState+0xc
02 00000000`00a2ece0 00007ffd`835be06d     wow64cpu!BTCpuSimulate+0xbb5
03 00000000`00a2ed20 00007ffd`835bd8ad     wow64!RunCpuSimulation+0xd
04 00000000`00a2ed50 00007ffd`851bf66d     wow64!Wow64LdrpInitialize+0x12d
05 00000000`00a2f000 00007ffd`851ad558     ntdll_7ffd850e0000!LdrpInitializeProcess+0x16d1
06 00000000`00a2f3c0 00007ffd`8515a843     ntdll_7ffd850e0000!_LdrpInitialize+0x52cdc
07 00000000`00a2f440 00007ffd`8515a76e     ntdll_7ffd850e0000!LdrpInitializeInternal+0x6b
08 00000000`00a2f6c0 00000000`00000000     ntdll_7ffd850e0000!LdrInitializeThunk+0xe
```

Also there seems to be a network connection from this process which I don't quite understand.

<hr>

Sadly I don't see any RWX memory in the active page tables. In order to look into this more I'd need to know where the RWX memory is located (if there is any at all).

**Comment by ufrisk** [comment]
apologies for not reading enough, there is indeed a VAD section pf private RWX, but it's not mapped by the memory manager into active process memory yet. No thread have been reading this VAD section yet.

Maybe I should make it so that FindEvil detects not yet fully started processes with private RWX memory in yet to be mapped VADs.

**Comment by ufrisk** [comment]
The memory in this RWX section is currently in compressed memory.

It would be good for me to:
1. Add private rwx VADs to the FindEvil (even if not yet loaded)
2. Detection of too few entries loaded in core dlls (such as ntdll) in FindEvil.
3. Possibly improving memory manager to retrieve more memory (file backed executables not yet mapped, such as the original .exe at 0xA70000). Would it be possible for me to take a look at this .exe?

**Comment by unk0unk0unk0** [comment]
Thank you so much for the detailed explanation. Of course it's possible. I will sent the link for it on twitter.

**Comment by ufrisk** [comment]
This should now be fixed. Please let me know if it works for you.

**Comment by unk0unk0unk0** [comment]
It works well on my environment. Thank you very much for your excellent works.
