### ISSUE TITLE
Unable to auto-identify operating system for PROC file system mount.

### ISSUE THREAD

**Issue by AAigars** [ufrisk/MemProcFS#99]
Hey, I was attempting to use the latest version (4.8.2) of MemProcFS on Debian Aarch64 however I kept encountering this error message: 

```
[+] using FTDI device: 0403:601f (bus 1, device 4)
[+] FTDIFTDI SuperSpeed-FIFO Bridge000000000001
[CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
VmmProc: Unable to auto-identify operating system for PROC file system mount.   
         Specify PageDirectoryBase (DTB/CR3) in -cr3 option if value if known.  
MOUNT: INFO: PROC file system not mounted.
```

Device: Screamer PCIe Squirrel
Entire Log: https://drive.google.com/file/d/1AUd0HmxCnVv8hcn1eB3Q52MO3foJSGUW/view

So I decided to try to use some older versions of MemProcFS which is where I noticed that version 4.2.3 works completely fine, but whenever I tried 4.3.6 or greater it no-longer worked. 

Do you have any idea why this is happening?

Thanks.

**Comment by ufrisk** [comment]
Thank you for reporting this issue. It should hopefully now be fixed in v4.8.3 which is available for download.

There has been quite a few updates since the older version and many bug fixes so I hope the experience will be much better than with the older version you were using.

Please let me know if it works for you.
